spring:
  profiles:
    default: default
    active: ${SPRING_PROFILES_ACTIVE:default}
  config:
    import: optional:file:.env.file[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  seed:
    enabled: false
    attributes:
      enabled: false
    variants:
      enabled: false
    categoryHierarchy:
      enabled: false
